# Generated by Django 4.2.1 on 2023-05-29 07:53

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_alter_product_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(default='', max_length=15)),
                ('full_name', models.CharField(default='', max_length=300)),
                ('province', models.CharField(default='', max_length=100)),
                ('province_code', models.IntegerField(default=0)),
                ('district', models.CharField(default='', max_length=100)),
                ('district_code', models.IntegerField(default=0)),
                ('ward', models.CharField(default='', max_length=100)),
                ('ward_code', models.IntegerField(default=0)),
                ('street', models.CharField(default='', max_length=300)),
                ('status', models.CharField(default='In progress', max_length=20)),
                ('total', models.IntegerField(default=0)),
                ('payment', models.TextField(default='COD')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=300)),
                ('img_urls', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('product', models.ManyToManyField(to='api.product')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.variation')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
