# Generated by Django 4.2.1 on 2023-05-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
