# Generated by Django 4.2.1 on 2023-05-30 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0015_alter_order_created_by_alter_review_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=15)),
                ('full_name', models.CharField(default='', max_length=300)),
                ('province', models.CharField(default='', max_length=100)),
                ('province_code', models.IntegerField(default=0)),
                ('district', models.CharField(default='', max_length=100)),
                ('district_code', models.IntegerField(default=0)),
                ('ward', models.CharField(default='', max_length=100)),
                ('ward_code', models.IntegerField(default=0)),
                ('street', models.CharField(default='', max_length=300)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', related_query_name='address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
    ]
