# Generated by Django 4.2.1 on 2023-05-30 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_payment_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
    ]
