# Generated by Django 4.2.1 on 2023-05-31 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_voucher_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exp',
            field=models.DateField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='variations_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
