# Generated by Django 4.2.1 on 2023-06-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_usedvoucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteitem',
            name='variation',
        ),
    ]
