# Generated by Django 4.2.1 on 2023-06-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_review_img_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='number',
            field=models.CharField(default='', max_length=30),
        ),
    ]
