# Generated by Django 4.2.1 on 2023-06-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_payment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cvc',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='number',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
