# Generated by Django 4.2.1 on 2023-06-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_product_composition_product_depth_product_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='composition',
            new_name='material',
        ),
    ]
