# Generated by Django 4.2.1 on 2023-06-21 02:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_product_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='img_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', null=True), blank=True, default=list, size=None),
        ),
    ]
