# Generated by Django 4.2.1 on 2023-06-24 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_review_img_urls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='depth',
            new_name='length',
        ),
    ]
